<a href="https://colab.research.google.com/github/AlejandroNPereyra/APIREST.dicegame/blob/main/Sprint_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Descripción

En este sprint trabajarás un proceso completo de **Exploratory Data Analysis (EDA)** utilizando **Python** y **Pandas**, simulando una situación real de análisis de datos dentro de una empresa.

El objetivo no es solo obtener resultados, sino **entender el dataset, detectar problemas, tomar decisiones analíticas y justificarlas**, siguiendo una metodología estructurada similar a la que utilizaría un/a analista de datos en un entorno profesional.

El sprint está organizado en **tres niveles de dificultad**, donde cada nivel profundiza más en:

- » Calidad de los datos.
- » Capacidad de diagnóstico.
- » Tratamiento de errores.
- » Enriquecimiento del dataset.

Procura que tu código sea **claro y organizado**.

---

# Nivel 1 - EDA estructurado y limpieza básica

Tenemos un dataset de empleados obtenido a partir de una encuesta interna. Antes de poder extraer conclusiones, hay que asegurarse de que los datos son correctos, consistentes y analizables.

## Ejercicio 1: Exploración inicial del dataset

🎯 **Objetivo:** entender la estructura general del dataset y detectar posibles problemas antes de empezar a limpiar o transformar datos.

En este ejercicio debes realizar una exploración inicial del DataFrame (`sprint8_complex.xlsx`) para responder, como mínimo, a las siguientes preguntas:

- » ¿Cuántas filas y columnas tiene el dataset?
- » ¿Qué tipo de datos contiene cada columna?
- » ¿Hay filas duplicadas?
- » ¿Los datos parecen coherentes a primera vista?
- » ¿Detectas posibles problemas o inconsistencias evidentes?

Para hacerlo, deberás:

- » Analizar las dimensiones del dataset
- » Mostrar una muestra representativa de filas
- » Revisar los tipos de variables
- » ¿Los datos parecen coherentes a primera vista?
- » Detectar filas duplicadas
- » Identificar y describir posibles problemas iniciales (sin solucionarlos todavía)

> **Importante**
>
> acompaña el código con un breve comentario explicando qué has observado y qué problemas crees que habrá que abordar en los ejercicios siguientes.

---

# Carga del dataset en Google Colab

Para trabajar con el archivo `sprint8_complex.xlsx` de forma permanente en Colab, se siguen dos pasos: montar Google Drive y leer el Excel con pandas.

In [44]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [45]:
import pandas as pd

ruta = '/content/drive/MyDrive/Colab Notebooks/Sprint 8/sprint8_complex.xlsx'

encuesta_raw = pd.read_excel(ruta)

In [46]:
# ---------- Muestra representativa inicial ----------
encuesta_raw.head(10)

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
5,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
6,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
8,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
9,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8

**A simple vista se pueden detectar dos grandes problemas estructurales.**

Las filas de la 1 a la 3 traen metadatos

Las filas 0-2 ("Dades de l'enquesta...", "Generades aleatòriament...", vacía) no son datos significativos. Hay que poder leer el Excel saltandose esas filas.

También notamos que el índice no se corresponde con el de la primera columna de la encuesta, dejamos solo el índice que es útil al dataframe.

In [54]:
encuesta = pd.read_excel(ruta, skiprows=3, index_col=0)
encuesta

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

**Encoding roto**

Gènere aparece como GÃ¨nere, Càrrec como CÃ rrec, Itàlia como ItÃ lia.

Esto es un problema de UTF-8 leído como Latin-1.

In [56]:
def fix_encoding(texto):
    """Corrige texto UTF-8 leído como Latin-1, pero solo si hace falta."""
    if not isinstance(texto, str):
        return texto
    try:
        return texto.encode('latin-1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        # Si falla, el texto ya estaba bien codificado
        return texto

# Corregimos los nombres de las columnas
encuesta.columns = [fix_encoding(c) for c in encuesta.columns]

# Finalmente corregimos los valores de texto
for col in encuesta.select_dtypes(include='object').columns:
    encuesta[col] = encuesta[col].apply(fix_encoding)

In [58]:
encuesta

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

Aún quedan problemas por resolver, pero ya que tenemos un dataset mejor estructurado, primero respondemos las preguntas relacionadas que faltan, para luego hacer un mejor análisis de los problemas presentes para enriquecer nuestro dataframe.

In [59]:
# ---------- Dimensiones ----------
print("Dimensiones (filas, columnas):", encuesta.shape)

Dimensiones (filas, columnas): (1007, 19)

In [60]:
# ---------- Tipos de datos e info general ----------
encuesta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1007 entries, 0 to 1006
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nom                         1006 non-null   object
 1   Cognoms                     1006 non-null   object
 2   DNI                         1006 non-null   object
 3   País d'origen               1006 non-null   object
 4   Ciutat                      1006 non-null   object
 5   Dia de Naixement            1006 non-null   float64
 6   Mes de Naixement            1006 non-null   float64
 7   Any de Naixement            1006 non-null   float64
 8   Gènere                      966 non-null    object
 9   Salari mensual              1006 non-null   object
 10  Fills                       419 non-null    object
 11  No Fills                    585 non-null    object
 12  Grup Professional           1005 non-null   object
 13  Càrrec                      1005 non-null   object
 14  Nombre_fills                709 non-null    float64
 15  Te_cotxe                    658 non-null    object
 16  Km_anuals                   315 non-null    float64
 17  Consum_mitja_L_100km        261 non-null    float64
 18  Temperatura_mitjana_ciutat  936 non-null    float64
dtypes: float64(7), object(12)
memory usage: 157.3+ KB

In [61]:
# ---------- Filas duplicadas ----------
print("Nº de filas duplicadas:", encuesta.duplicated().sum())

Nº de filas duplicadas: 4

In [63]:
# Duplicados exactos (originales y copias)
df_dup_exactos = encuesta[encuesta.duplicated(keep=False)]
display(df_dup_exactos.sort_values(by=list(encuesta.columns)))

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
372,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
730,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
464,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1001,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9

# Ejercicio 2: Validaciones básicas de los datos y decisiones de eliminación

🎯 **Objetivo:** asegurar que los datos cumplen unas condiciones mínimas de calidad y determinar qué filas pueden seguir siendo analizadas y cuáles deben descartarse.

En este ejercicio deberás validar aspectos clave del dataset que son críticos en cualquier contexto real de análisis de datos, tomando decisiones justificadas sobre la validez o eliminación de registros.

**Aspectos a validar:**

- » ¿Existen identificadores únicos (DNI) para cada persona?
- » ¿Qué harás con las filas duplicadas o registros repetidos?
- » ¿Hay valores obligatorios que faltan o información incoherente?
- » ¿Detectas formatos incorrectos, errores de codificación o valores imposibles?

**Concretamente, deberás:**

- » Corregir posibles problemas de codificación y acentuación en los nombres de las columnas y en los valores de texto, si procede.
- » Detectar y eliminar filas duplicadas exactas, indicando cuántos registros se han eliminado.
- » Comprobar la unicidad del DNI. En caso de detectar DNIs duplicados, deberás analizar la coherencia de la información asociada y descartar o anular los registros que no sean fiables, justificando claramente la decisión tomada.
- » Identificar los campos clave que no deberían contener valores nulos, detectar registros con información insuficiente y eliminar únicamente aquellas filas completamente vacías o con información irrecuperable o no sustituible, explicando por qué no es posible ni razonable imputarlas.

> **Importante**
>
> en este ejercicio no se espera que imputes datos, sino que decidas qué registros pueden formar parte del análisis y cuáles no, argumentando siempre el criterio utilizado.

🧠 Si el texto "se entiende pero está mal escrito" → codificación

Si el texto "está bien escrito pero no es útil para el análisis" → validación

# Ejercicio 3: Transformaciones necesarias y preparación del dataset

🎯 **Objetivo:** preparar el dataset para que sea coherente, analizable y estructuralmente correcto antes de realizar cualquier análisis descriptivo.

En este ejercicio deberás aplicar transformaciones básicas pero esenciales, orientadas a mejorar la calidad de los datos y facilitar el análisis posterior.

**Aspectos a revisar y transformar:**

- » ¿Los valores categóricos están normalizados y son consistentes?
- » ¿Los valores nulos son coherentes con la información disponible?
- » ¿Hay redundancia de variables que pueda generar problemas analíticos?
- » ¿Las variables contextuales (como temperatura, salario) están completas y preparadas para el análisis?

**Concretamente, deberás:**

- » Normalizar los valores categóricos para evitar ambigüedades (por ejemplo, valores que representan el mismo concepto pero están escritos de manera diferente).
- » Revisar la coherencia de los valores nulos, asegurando que:
  - Las personas que tienen kilometraje anual y consumo medio asociados disponen de coche. En los casos en que conste consumo medio pero no kilometraje anual, habrá que decidir cómo resolver esta incoherencia de manera justificada.
  - Las personas que tienen un valor en el número de hijos efectivamente tienen hijos.
- » Unificar la información sobre hijos en una única columna, ya que mantener varias columnas con información complementaria no es óptimo y puede generar problemas analíticos (redundancia o multicolinealidad).
- » Validar la temperatura media. En caso de que esta información falte, deberás imputarla utilizando un criterio razonable (por ciudad o por un nivel superior justificado).
- » Revisar e imputar los salarios faltantes, aplicando criterios analíticos coherentes (como por ejemplo cargo, grupo profesional, ciudad, género o franja de edad).

> **Importante**
>
> en este ejercicio no se trata de eliminar registros, sino de transformar, normalizar y preparar los datos para que sean analizables de manera rigurosa en los niveles siguientes.

# Ejercicio 4: Primeros análisis descriptivos

🎯 **Objetivo:** obtener una primera visión global del dataset una vez aplicadas las transformaciones básicas, mediante estadísticas descriptivas y comparaciones simples entre grupos relevantes.

**Aspectos a revisar y analizar:**

- » Construir tablas resumen descriptivas.
- » Hacer comparaciones básicas entre grupos relevantes.

**Concretamente, deberás:**

- » Construir tablas resumen descriptivas de salarios, como una tabla resumen que permita ver el sueldo medio, mediana, mínimo y máximo por Género. Ordena la tabla en función del sueldo medio.
- » Crear una tabla resumen con el salario medio por género (filas) y país de origen (columnas). Añade las medias en los márgenes de la tabla. Aplica formato condicional a la tabla para ver en un color más intenso los valores más elevados.

**(EXTRA)**

Antes de interpretar medias, medianas o totales, hay que preguntarse si estos valores permiten una comparación justa entre grupos. Cuando los tamaños de los grupos son diferentes, los porcentajes o ratios suelen ofrecer una visión más objetiva que los valores absolutos.

¿Podrías repetir el análisis utilizando porcentajes y ratios salariales, y comparar cómo cambia la interpretación respecto a los valores absolutos?

# Nivel 2 - Análisis con datos enriquecidos y estructuras múltiples

Para este nivel, se facilita información externa que simula datos reales utilizados por una empresa en procesos de análisis y toma de decisiones salariales.

- » **Archivo JSON de política salarial:** La empresa dispone de un archivo JSON que define las reglas de incremento salarial anual. Este documento establece incrementos base por grupo profesional y ajustes adicionales según factores personales (edad, hijos) y contextuales. Este tipo de estructura es habitual en sistemas internos de recursos humanos, ya que permite modificar las políticas sin alterar el código.
- » **Archivo CSV de ciudades europeas:** Se proporciona también un archivo CSV con información contextual sobre diversas ciudades europeas (país, índice de coste de vida, calidad del transporte público y tipo de clima). Este dataset representa una fuente externa de datos utilizada para enriquecer el análisis salarial en función del entorno geográfico donde reside cada persona.

## Ejercicio 1: Enriquecimiento mediante datasets externos

🎯 **Objetivo:** ampliar el dataset principal integrando información contextual externa y evaluar el impacto analítico de las decisiones de fusión.

**Aspectos a revisar y analizar:**

- » ¿Las diferentes fuentes de datos son coherentes y compatibles entre sí para poder calcular un salario ajustado?
- » ¿La información contextual incorporada (coste de vida, políticas salariales) es suficiente para aplicar incrementos de manera consistente?
- » ¿Hay vacíos de información que impidan calcular correctamente el incremento salarial en algunos registros?
- » ¿Es necesario tomar decisiones analíticas cuando la información contextual es parcial o ausente?
- » ¿Cómo pueden estas decisiones influir en el cálculo del salario ajustado y en su interpretación posterior?

**Concretamente, deberás:**

- » Integrar el dataset principal con:
  - El dataset contextual de ciudades.
  - La política salarial definida en formato JSON.
- » Calcular un incremento salarial total combinando:
  - Grupo profesional.
  - Situación familiar.
  - Franja de edad.
  - Coste de vida de la ciudad.
- » Identificar qué registros no pueden recibir alguno de los ajustes y explicar el motivo.
- » Decidir, de manera razonada, cómo tratar estos casos en el cálculo del salario ajustado, justificando el impacto analítico de la decisión tomada.

> **Importante**
>
> El objetivo no es solo enriquecer datos, sino demostrar criterio analítico en la gestión de la incertidumbre y entender cómo las decisiones de integración condicionan los análisis posteriores.

# Ejercicio 2: Reestructuración del dataset

🎯 **Objetivo:** preparar el dataset para análisis comparativos y/o visuales. Convertir información dispersa en formato largo:
- Salarios
- Movilidad
- Contexto climático
- etc.

**Aspectos a revisar y analizar:**

- » ¿Existen variables que representan conceptos similares o relacionados, pero están distribuidas en diferentes columnas?
- » El formato actual del dataset facilita o dificulta:
  - comparaciones entre magnitudes.
  - agregaciones por grupos.
- » ¿Qué impacto tiene la forma del dataset (ancho vs largo) en la lectura e interpretación de los datos?

**Concretamente, deberás:**

- » Reestructurar el dataset utilizando `melt()` para convertirlo a formato largo, definiendo previamente:
  - las columnas que actúan como identificadoras (por ejemplo: persona, ciudad, grupo profesional, género, etc.).
  - las columnas que pasan a representar valores medidos (por ejemplo: salarios, movilidad, variables contextuales).
- » Analizar por qué el formato largo es más adecuado para:
  - realizar comparaciones entre diferentes tipos de variables.
  - calcular estadísticos agregados.

📌 **Nota**

No se busca generar visualizaciones en este punto, sino preparar correctamente los datos para hacerlo en ejercicios posteriores.

# Ejercicio 3: Creación de variables derivadas (Feature Engineering)

🎯 **Objetivo:** generar nuevas variables derivadas a partir de la información existente y evaluar su calidad analítica. Aunque algunas variables de base (como la edad o el salario) ya han sido introducidas en ejercicios anteriores, en este nivel no se valora su creación técnica, sino la capacidad de transformarlas en indicadores más informativos, la detección de casos límite o incoherentes y la reflexión sobre la utilidad real de las variables generadas en un contexto analítico.

**Ejemplos (elección guiada):**

- » Índice de dependencia familiar: Salario mensual / (Número hijos + 1).
- » Índice de movilidad: Km anuales / Temperatura media.
- » Ratio salario / coste de vida.
- » Indicador de dependencia familiar: Salario / Número hijos.
- » Peso de responsabilidad familiar: Número hijos * Edad.
- » Indicador de etapa vital: 0 → sin cargas, 1 → etapa activa, 2 → alta dependencia.

**Concretamente, deberás:**

- » Crear al menos 3 variables derivadas.
- » Justificar:
  - Su utilidad analítica.
  - Las decisiones tomadas.
- » Detectar casos límite o incoherentes generados por las nuevas variables.

📌 **Nota**

El feature engineering se realiza sobre el dataset en formato ancho, ya que la creación de variables derivadas requiere combinar información de naturaleza diferente. El formato largo se utiliza posteriormente para facilitar comparaciones, agregaciones y análisis descriptivos de las variables generadas.

# Ejercicio 4: Exportación y síntesis de resultados

🎯 **Objetivo:** consolidar los resultados obtenidos tras la preparación, enriquecimiento y creación de variables, y generar salidas estructuradas reutilizables para análisis o reporting.

En este ejercicio se quiere poner el foco en:

- » La organización de los datos por grupos relevantes.
- » La generación de datasets finales coherentes.
- » La capacidad de sintetizar información clave.

**Aspectos a revisar y analizar:**

- » ¿Qué nivel de agrupación es más adecuado para la exportación de resultados?
- » ¿Cómo separar datos detallados de datos agregados?
- » ¿Qué información es relevante para un uso posterior (análisis, visualización, reporting)?

**Concretamente, deberás:**

- » Utilizando un bucle, exportar en 4 archivos (formato `.csv` o `.xlsx`) los datos correspondientes a cada Grupo Profesional. Por ejemplo: `dades_GrupA.csv`, `dades_GrupB.csv`...
- » Crear y exportar un quinto DataFrame (formato `.csv` o `.xlsx`) que contenga, para cada Grupo Profesional:
  - Número total de trabajadores.
  - Salario medio.
  - Edad mediana.

**(EXTRA)**

Explora cómo exportar todos los DataFrames en un único archivo Excel, utilizando:

- » Una pestaña para cada Grupo Profesional.
- » Una pestaña adicional con el resumen agregado.

📌 **Nota**

No se valora la complejidad técnica, sino la claridad, el orden y la coherencia de las salidas generadas.

# Nivel 3 – Exploración visual y optimización aplicada

En este nivel se trabaja con un dataset ya rico y complejo, con múltiples variables personales, salariales, contextuales y derivadas. El objetivo no es seguir limpiando datos, sino extraer valor rápidamente y aplicar el dataset a un problema práctico.

El nivel se divide en dos ejercicios:

- » **Exploración visual automatizada**, para obtener una visión global del dataset, detectar patrones, anomalías o relaciones relevantes sin análisis manual exhaustivo.
- » **Resolución de un problema aplicado**, donde los datos sirven como soporte para tomar decisiones operativas reales, aunque la solución no sea matemáticamente óptima.

👉 El foco está en el criterio analítico, la capacidad de síntesis y la justificación de decisiones, no en la perfección técnica.

## Ejercicio 1: Exploración visual del dataset

🌍 **Contexto:** Se dispone de un DataFrame con un volumen elevado de variables. Antes de cualquier análisis específico, es necesario disponer de mecanismos que permitan explorar el dataset de manera rápida y sistemática.

Este ejercicio se centra en crear una función que ayude a crear (y exportar) un gráfico automáticamente para cada columna del dataframe. Por ejemplo, un histograma/boxplot si la variable es numérica, unas barras de los valores más frecuentes si es categórica y unas barras de los años más frecuentes si el dato está en formato fecha.

📌 **Nota**

Muestra el resultado de la función en alguno de los datasets de ejemplo que contiene el paquete seaborn. Por ejemplo, `iris`, `penguins` o `titanic`.

# Ejercicio 2: Optimización de rutas (problema aplicado)

🌍 **Contexto:** La empresa no dispone de un control fiable del kilometraje de los desplazamientos de sus trabajadores. Antes de implementar un sistema avanzado, se quiere hacer una prueba piloto con trabajadores ubicados en España.

Para esta prueba:

- » Se trabaja con una matriz de distancias entre ciudades.
- » Se quiere una solución simple, razonable y explicable.
- » No se busca la ruta óptima, sino una aproximación coherente.

Carga el archivo `matriu_distancies.xlsx` en pandas de manera que las filas y columnas sean las ciudades y se eliminen `"Las Palmas de Gran Canaria"` y `"Palma"`.

Desarrolla una función que:

- » Reciba: una ciudad de origen y una ciudad de destino.
- » Devuelva: el orden de las ciudades visitadas (ruta) y la distancia total recorrida.

La ruta se debe construir siguiendo una estrategia sencilla: ir siempre a la ciudad no visitada más cercana hasta llegar al destino.